"""Add devices and zone mappings

Revision ID: d62cac8f8ad8
Revises: 1001716f9e55
Create Date: 2021-12-06 18:12:33.969394+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd62cac8f8ad8'
down_revision = '1001716f9e55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('manufacturer_id', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('manufacturer', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_unique_manufacturer_manufacturer_id_model', 'devices', ['manufacturer_id', 'manufacturer', 'model'], unique=True)
    op.create_table('device_zones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('pin_num', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_zones_device_id'), 'device_zones', ['device_id'], unique=False)
    op.create_index(op.f('ix_device_zones_zone_id'), 'device_zones', ['zone_id'], unique=False)
    op.create_index('ix_unique_device_id_zone_id_pin', 'device_zones', ['device_id', 'zone_id', 'pin_num'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_unique_device_id_zone_id_pin', table_name='device_zones')
    op.drop_index(op.f('ix_device_zones_zone_id'), table_name='device_zones')
    op.drop_index(op.f('ix_device_zones_device_id'), table_name='device_zones')
    op.drop_table('device_zones')
    op.drop_index('ix_unique_manufacturer_manufacturer_id_model', table_name='devices')
    op.drop_table('devices')
    # ### end Alembic commands ###
