version: '3'
services:
  web:
    image: rpi-lts-ctrl-service:dev
    expose:
      - 5000
    ports:
      - 5000:5000
    env_file:
      - ./docker-local.env
    depends_on:
      - postgres
      - db-data-seed
    devices:
      - /dev/null:/dev/gpiomem
    networks:
      - rpi-lts-ctrl-net
    stdin_open: true
    tty: true
    volumes:
      - /etc/localtime:/etc/localtime
  monitor:
    image: rpi-lts-ctrl-monitor:dev
    depends_on:
      - web
    env_file:
      - ./docker-local.env
    networks:
      - rpi-lts-ctrl-net
    volumes:
      - /etc/localtime:/etc/localtime
  postgres:
    image: postgres:12-alpine
    expose:
      - 5432
    ports:
      - 5432:5432
    networks:
      - rpi-lts-ctrl-net
    env_file:
      - ./docker-local.env
  db-data-seed:
    image: rpi-lts-ctrl-db-seed:dev
    depends_on:
      - postgres
    env_file:
      - ./docker-local.env
    networks:
      - rpi-lts-ctrl-net
networks:
  rpi-lts-ctrl-net:
      